CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    metadata JSONB
);

INSERT INTO users (name, metadata) VALUES
('Alice', {age: 30, city: 'NYC', email: 'alice@ex.com', active: true, roles: ['admin'], profile: {lang: 'en', timezone: 'UTC-5'}}),
('Bob', {age: 25, city: 'NYC', email: 'bob@ex.com', active: true, roles: ['user'], profile: {lang: 'en'}, address: {street: 'Main St', zip: 10001}}),
('Carol', {age: 35, city: 'Berlin', email: 'carol@ex.com', active: false, roles: ['user', 'moderator'], hobbies: ['reading', 'gaming', 'coding']}),
('Dave', {age: 28, city: 'London', email: 'dave@ex.com', active: true, roles: ['user'], profile: {lang: 'en', theme: 'dark'}}),
('Eve', {age: 22, city: 'Paris', email: 'eve@ex.com', active: true, roles: ['user'], hobbies: ['music', 'travel'], verified: true}),
('Frank', {age: 41, city: 'Tokyo', email: 'frank@ex.com', active: false, roles: ['user'], profile: {lang: 'jp'}, last_login: '2024-10-01'}),
('Grace', {age: 19, city: 'Toronto', email: 'grace@ex.com', active: true, roles: ['user'], student: true}),
('Heidi', {age: 33, city: 'Amsterdam', email: 'heidi@ex.com', active: true, roles: ['admin'], permissions: {db: true, billing: false}}),
('Ivan', {age: 27, city: 'São Paulo', email: 'ivan@ex.com', active: true, roles: ['user'], profile: {lang: 'pt', timezone: 'UTC-3'}}),
('Judy', {age: 45, city: 'NYC', email: 'judy@ex.com', active: false, roles: ['user'], children: 2}),
('Liam', {age: 21, city: 'Berlin', active: true, roles: ['user'], hobbies: ['gaming'], profile: {lang: 'de'}}),
('Noah', {age: 22, city: 'Berlin', active: true, roles: ['user'], verified: false}),
('Emma', {age: 23, city: 'Berlin', active: false, roles: ['user'], banned: true, ban_reason: 'spam'}),
('Olivia', {age: 24, city: 'London', active: true, roles: ['user'], profile: {theme: 'light'}}),
('Ava', {age: 25, city: 'London', active: true, roles: ['user'], profile: {theme: 'dark'}}),
('Sophia', {age: 26, city: 'London', active: false, roles: ['user'], last_login: '2023-12-01'}),
('Mason', {age: 27, city: 'Tokyo', active: true, roles: ['user'], devices: ['mobile', 'desktop']}),
('Lucas', {age: 28, city: 'Tokyo', active: true, roles: ['user'], devices: ['desktop']}),
('Ethan', {age: 29, city: 'Tokyo', active: false, roles: ['user'], devices: []}),
('Logan', {age: 30, city: 'Toronto', active: true, roles: ['user'], newsletter: true}),
('Ella', {age: 31, city: 'Toronto', active: true, roles: ['user'], newsletter: false}),
('Mia', {age: 32, city: 'Toronto', active: false, roles: ['user'], email_verified: true}),
('Charlotte', {age: 33, city: 'Amsterdam', active: true, roles: ['user'], hobbies: ['photography']}),
('Amelia', {age: 34, city: 'Amsterdam', active: true, roles: ['user'], hobbies: ['cooking', 'coffee']}),
('Harper', {age: 35, city: 'Amsterdam', active: false, roles: ['user'], hobbies: null}),
('Mateus', {age: 36, city: 'São Paulo', active: true, roles: ['user'], profile: {lang: 'pt'}}),
('Rafael', {age: 37, city: 'São Paulo', active: true, roles: ['user'], profile: {lang: 'pt', timezone: 'UTC-3'}}),
('Bruno', {age: 38, city: 'São Paulo', active: false, roles: ['user'], failed_logins: 5}),
('Daniel', {age: 39, city: 'NYC', active: true, roles: ['user'], profile: {lang: 'en'}, quota: 1024}),
('Michael', {age: 40, city: 'NYC', active: true, roles: ['user'], quota: 2048}),
('Sarah', {age: 41, city: 'NYC', active: false, roles: ['user'], quota: 0}),
('Jonas', {age: 42, city: 'Berlin', active: true, roles: ['moderator'], permissions: {delete: true}}),
('Felix', {age: 43, city: 'Berlin', active: true, roles: ['moderator'], permissions: {delete: false}}),
('Oliver', {age: 44, city: 'London', active: true, roles: ['admin'], permissions: {all: true}}),
('Henry', {age: 45, city: 'London', active: false, roles: ['admin'], permissions: {all: false}}),
('Kenji', {age: 46, city: 'Tokyo', active: true, roles: ['user'], api_keys: 2}),
('Hiro', {age: 47, city: 'Tokyo', active: true, roles: ['user'], api_keys: 0}),
('Nathan', {age: 48, city: 'Toronto', active: false, roles: ['user'], suspended_until: '2025-01-01'}),
('Sven', {age: 49, city: 'Amsterdam', active: true, roles: ['user'], beta_user: true}),
('Paulo', {age: 50, city: 'São Paulo', active: true, roles: ['user'], beta_user: false});

