name: rust ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: Run tests
      run: cargo test --workspace --verbose

  os-check:
  # run cargo test on mac and windows
  runs-on: ${{ matrix.os }}
  name: ${{ matrix.os }} / stable
  strategy:
    fail-fast: false
    matrix:
      os: [macos-latest] # for while, no windows 
      # os: [macos-latest, windows-latest]
  steps: 
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install stable
      uses: dtolnay/rust-toolchain@stable
    - name: cargo generate-lockfile
      if: hashFiles('Cargo.lock') == ''
      run: cargo generate-lockfile
    - name: cargo test
      run: cargo test --locked --all-features --all-targets
